# Generated by Django 5.0.4 on 2025-06-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('transaction_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'blockchain_balances',
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('previous_hash', models.CharField(max_length=64)),
                ('merkle_root', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('nonce', models.BigIntegerField()),
                ('difficulty', models.IntegerField()),
                ('transaction_count', models.IntegerField(default=0)),
                ('block_size', models.IntegerField(default=0)),
                ('miner_address', models.CharField(blank=True, max_length=100, null=True)),
                ('block_reward', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'blockchain_blocks',
                'ordering': ['-index'],
            },
        ),
        migrations.CreateModel(
            name='MiningPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miner_address', models.CharField(max_length=100)),
                ('hash_rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('blocks_mined', models.IntegerField(default=0)),
                ('total_rewards', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('last_block_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blockchain_mining_pool',
                'ordering': ['-hash_rate'],
            },
        ),
        migrations.CreateModel(
            name='NetworkStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_blocks', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_supply', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('circulating_supply', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('price_usd', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('network_hash_rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('difficulty', models.IntegerField(default=2)),
                ('avg_block_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_transactions', models.IntegerField(default=0)),
                ('active_addresses', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'blockchain_network_stats',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StakingPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator_address', models.CharField(max_length=100)),
                ('staked_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('delegated_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('slashed', 'Slashed')], default='active', max_length=20)),
                ('blocks_validated', models.IntegerField(default=0)),
                ('total_rewards', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('slashing_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blockchain_staking_pool',
                'ordering': ['-total_amount'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('encrypted_private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('mnemonic_encrypted', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'blockchain_wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('from_address', models.CharField(max_length=100)),
                ('to_address', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('mining', 'Mining Reward'), ('fee', 'Transaction Fee')], default='transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('signature', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('gas_used', models.IntegerField(default=0)),
                ('gas_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('nonce', models.IntegerField(default=0)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.block')),
            ],
            options={
                'db_table': 'blockchain_transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=100, unique=True)),
                ('creator_address', models.CharField(max_length=100)),
                ('contract_code', models.TextField()),
                ('abi', models.JSONField(default=dict)),
                ('bytecode', models.TextField()),
                ('status', models.CharField(choices=[('deployed', 'Deployed'), ('paused', 'Paused'), ('destroyed', 'Destroyed')], default='deployed', max_length=20)),
                ('gas_limit', models.IntegerField(default=1000000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creation_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.transaction')),
            ],
            options={
                'db_table': 'blockchain_smart_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegator_address', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rewards_earned', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='blockchain.stakingpool')),
            ],
            options={
                'db_table': 'blockchain_delegations',
                'ordering': ['-amount'],
                'unique_together': {('delegator_address', 'validator')},
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_address'], name='blockchain__from_ad_5c42fe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_address'], name='blockchain__to_addr_bf4c26_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='blockchain__status_946598_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp'], name='blockchain__timesta_e2c367_idx'),
        ),
    ]
