# Generated by Django 5.0.4 on 2025-07-02 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending_notification', 'Pending Notification'), ('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending_notification', max_length=25),
        ),
        migrations.CreateModel(
            name='TransactionNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_address', models.CharField(max_length=100)),
                ('sender_address', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('incoming_transfer', 'Incoming Transfer'), ('outgoing_transfer', 'Outgoing Transfer'), ('mining_reward', 'Mining Reward')], default='incoming_transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='blockchain.transaction')),
            ],
            options={
                'db_table': 'blockchain_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionConfirmation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_address', models.CharField(max_length=100)),
                ('confirmation_type', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('auto_accept', 'Auto Accept')], max_length=20)),
                ('signature', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by_private_key', models.BooleanField(default=False)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='blockchain.transaction')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='blockchain.transactionnotification')),
            ],
            options={
                'db_table': 'blockchain_confirmations',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionnotification',
            index=models.Index(fields=['recipient_address'], name='blockchain__recipie_bb8818_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionnotification',
            index=models.Index(fields=['status'], name='blockchain__status_9501ae_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionnotification',
            index=models.Index(fields=['created_at'], name='blockchain__created_495e32_idx'),
        ),
    ]
